# Generated by Django 5.1.1 on 2024-09-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pomodorotimer_break_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorotimer',
            name='long_break',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
