# Generated by Django 5.1.1 on 2024-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pomodorotimer_break_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorotimer',
            name='current_state',
            field=models.CharField(default='inactive', max_length=200),
        ),
    ]
