# Generated by Django 5.1.1 on 2024-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pomodorotimer_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorotimer',
            name='breaks_until_long_break',
            field=models.IntegerField(default=-1),
        ),
    ]
